name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build web app
        # keep your existing script; change if needed
        run: yarn build:web

      - name: Debug - list potential build outputs
        run: |
          echo "apps/web:"
          ls -la apps/web || true
          echo "build candidates:"
          ls -la apps/web/build || ls -la apps/web/out || ls -la apps/web/.output || ls -la apps/web/dist || true

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # used for PR comments & actions
          action: "upload"
          app_location: "apps/web"                  # where package.json for the app is
          api_location: ""                          # set if you have an API folder (e.g. apps/api)
          app_artifact_location: "apps/web/build"   # change to actual build folder (out/.output/dist) if different
