name: Deploy Web to Azure App Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install and build Web
        run: |
          yarn install --frozen-lockfile
          yarn build:web
        env:
          CI: true

      - name: Deploy Web to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: "YOUR_WEB_APP_SERVICE_NAME"   # e.g. alpha-web-app
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
          package: apps/web