name: Deploy Web App to Azure (Free F1)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build Web App
        run: |
          yarn install --frozen-lockfile
          yarn build:web

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "alpha-web-app"
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
          package: apps/web
